export const REQ_ACTIVITY = "REQ_ACTIVITYT"
export const REQ_FAILURE_ACTIVITY = 'REQ_FAILURE_ACTIVITY';
export const UPCOMING_ACTIVITY="UPCOMING_ACTIVITY"
export const ACTIVE_ACTIVITY="ACTIVE_ACTIVITY"
export const COMPLETED_ACTIVITY="COMPLETED_ACTIVITY"
export const CREATE_ACTIVITY="CREATE_ACTIVITY"
export const GET_ACTIVITY_BY_USERID="GET_ACTIVITY_BY_USERID"
export const JOIN_USER="JOIN_USER"

