export const REQ_CHAT = "REQ_CHAT"
export const REQ_FAILURE_CHAT = "REQ_FAILURE_CHAT"
export const GET_ALL_CHAT_USERID = "GET_ALL_CHAT_BY_USERID"
export const GET_CHAT_DETAILS = "GET_CHAT_DETAILS"
export const FILTERED='FILTERED'
export const CREATE_GROUP = "CREATE_GROUP"
export const ADD_USER_IN_GROUP = "ADD_USER_IN_GROUP"

